name: alarm_cycle
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^4.0.7
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size  
  flutter_local_notifications: ^19.2.0
  intl: ^0.20.2
  path_provider: ^2.1.0
  provider: ^6.1.5
  path: ^1.8.3
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.9 # newer version was INFECT (till 10.1.2 !). Version 9.2.2 works !
  archive: ^4.0.2
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  flutter_background_service_ios: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
